#release configuration
#Tue Nov 05 22:32:57 GMT 2019
projectVersionPolicyId=default
scm.tagNameFormat=@{project.artifactId}-@{project.version}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
pushChanges=true
completedPhase=check-poms
scm.url=scm\:git\:git@bitbucket.org\:simon_massey/thinbus-srp-js.git
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
